joint_limits:
  openarm_left_joint1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  openarm_left_joint2:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  openarm_left_joint3:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 4.0
  openarm_left_joint4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 4.0
  openarm_left_joint5:
    has_velocity_limits: true
    max_velocity: 6.3
    has_acceleration_limits: true
    max_acceleration: 6.0
  openarm_left_joint6:
    has_velocity_limits: true
    max_velocity: 6.3
    has_acceleration_limits: true
    max_acceleration: 6.0
  openarm_left_joint7:
    has_velocity_limits: true
    max_velocity: 6.3
    has_acceleration_limits: true
    max_acceleration: 6.0
  openarm_right_joint1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  openarm_right_joint2:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0
  openarm_right_joint3:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 4.0
  openarm_right_joint4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 4.0
  openarm_right_joint5:
    has_velocity_limits: true
    max_velocity: 6.3
    has_acceleration_limits: true
    max_acceleration: 6.0
  openarm_right_joint6:
    has_velocity_limits: true
    max_velocity: 6.3
    has_acceleration_limits: true
    max_acceleration: 6.0
  openarm_right_joint7:
    has_velocity_limits: true
    max_velocity: 6.3
    has_acceleration_limits: true
    max_acceleration: 6.0
